### ISSUE TITLE
pip install 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/gf_kernel#2]
first, in the README "direct pip" install should be described first

When I did that, I get 
```
... graphviz 2.40.1 is already installed and up-to-date
MiKo:~ kohlhase$ which gf
/usr/local/bin/gf
MiKo:~ kohlhase$ pip install gf-kernel
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting gf-kernel
  Downloading https://files.pythonhosted.org/packages/26/29/f221fa1da96bbd93180fed121f83e02230a579b12b48433d2bdf3e63fe1b/gf_kernel-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9d/vk8_ls9d0_v0_bb4g7ncx90c0000gn/T/pip-install-S5rNLV/gf-kernel/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9d/vk8_ls9d0_v0_bb4g7ncx90c0000gn/T/pip-install-S5rNLV/gf-kernel/
 ```
I have python3 installed.

**Comment by kohlhase** [comment]
`pip3 install gf-kernal` did the trick. 
I think the README should be updated with a python2/3 caveat. 
My homebrew installation is the default one for python, and there must be other users like me.

**Comment by kohlhase** [comment]
Morever, trying to follow the installation with python3 (guessed) I get 
```
MiKo:~ kohlhase$ python3 -m gf_kernel.install
/usr/local/bin/python3: Error while finding module specification for 'gf_kernel.install' (ModuleNotFoundError: No module named 'gf_kernel')
```
even though the `gf-kernel` seems to be there. 
```
MiKo:~ kohlhase$ pip3 search gf-kernel
gf-kernel (1.0.0)                                - Simple example kernel for GF
  INSTALLED: 1.0.0 (latest)
```

**Comment by jfschaefer** [comment]
Concerning the first issue that `pip` might be linked to `pip2`: Is it possible to create a more meaningful error message if the wrong python version is used?

**Comment by kohlhase** [comment]
> Is it possible to create a more meaningful error message if the wrong python version is used?

I do not know how.

**Comment by tkw1536** [comment]
1) The README says: 
> This package requires Python 3 (or newer) and this README assumes that this is the default python version. If in doubt, use `python3` instead of `python` and `python3 -m pip` instead of `pip`.

is that not clear enough?

2) I am not sure what is going on in the second case, I can not reproduce this on my machine. Could it be that the pip problems caused errors while installing?

**Comment by step21** [comment]
The secod case might very well be that there are conflicting python versions, they are running one but module is installed somewhere else. People unfortunately have to organize their python versions themselves or use virtualnv or similar.
